us_deaths <- read.csv("data/us_deaths.csv")
la_deaths <- subset(us_deaths, Admin2 == "Los Angeles")
View(la_deaths)
la_deaths$Date <- as.Date(la_deaths$Date, format="%Y-%m-%d")
la_deaths$DateNumeric <- as.numeric(la_deaths$Date - min(la_deaths$Date))
mean(la_deaths$Case)
sd(la_deaths$Case)
plot(la_deaths$DateNumeric, la_deaths$Case, xlab = "Date", ylab = "total number of deaths")
cor(la_deaths$DateNumeric, la_deaths$Case)
fit <- lm(la_deaths$Case ~ la_deaths$DateNumeric)
fit
abline(-2604, 45.93)
test_result <- t.test(la_deaths$Case, mu=134.952453767264, alternative = "greater")
View(test_result)
#print(test_results)
us_deaths$Date <- as.Date(us_deaths$Date, format="%Y-%m-%d")
us_deaths$DateNumeric <- as.numeric(us_deaths$Date - min(us_deaths$Date))
plot(us_deaths$DateNumeric, us_deaths$Case)
cor(us_deaths$DateNumeric, us_deaths$Case)
fit <- lm(us_deaths$Case ~ us_deaths$DateNumeric)
fit